version: '3'
services:
  webradio:
    container_name: webradio
    build: .
    volumes:
        - ./:/usr/src/app
        - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    command: npm start
